dotenv: .env
networks:
  default: development
  sepolia:
    verify: True
  development:
    verify: False
  mainnet-fork:
    verify: False
  ganache-local:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
