dotenv: .env
networks:
  default: development
  no_deploy: True
  sepolia:
    verify: True
  ganache-local:
    verify: False
    no_deploy: True
  mainnet-fork:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  dummy_key: ${DUMMY_PRIVATE_KEY}